### ISSUE TITLE
Missing styleguide css?

### ISSUE THREAD

**Issue by zomars** [bobdenotter/bolt-foundation-theme#2]
I'm trying to preview the styleguide.twig template, but I doesn't find the `/assets/css/app.css` file anywhere. Is it part of Foundation? Bolt? Or maybe I'm missing something?

Any help is appreciated.

Cheers.

**Comment by bobdenotter** [comment]
I think that file's not needed.. What does it look like for you? Like this: 

![screenshot 2016-05-12 22 13 04](https://cloud.githubusercontent.com/assets/1833361/15228987/0c0c399c-188f-11e6-83d4-0ce8e6f9db6d.png)

**Comment by zomars** [comment]
It’s looking like this:

![captura de pantalla 2016-05-12 a las 3 12 19 p m](https://cloud.githubusercontent.com/assets/3504472/15230682/286f8002-1854-11e6-84b8-b8d4726bb57f.png)
